### PR TITLE
Renamed Kiev to Kyiv

### PR DESCRIPTION
**Pull request by shlomisas**
We're using this package in our project and I think it'll be better to have the right official name in it. 

Thank you! 🙏 

Source: https://en.wikipedia.org/wiki/KyivNotKiev#:~:text=In%20June%202019%2C%20at%20the,federal%20government%20of%20the%20United

image

### CODE REVIEW

**Review by imatveev — APPROVED** [review]

**Review by epsyan — APPROVED** [review]

**Comment by rogierschouten** [comment]
Hi guys, thank you for your PR. However, I cannot merge it because this package is auto-generated,.  Merging these changes would cause thousands of systems to break. 

If you want to get this changed, please contact Paul Eggert and his team from the [IANA timezone database](https://www.iana.org/time-zones).  Tell them to move the old name to a legacy zone and add the new name as a new zone, so that older systems keep working. 

Once a new version of the TZ database is released by IANA, this package will automatically reflect the changes.

**Comment by shlomisas** [comment]
> Hi guys, thank you for your PR. However, I cannot merge it because this package is auto-generated,. Merging these changes would cause thousands of systems to break.
> 
> If you want to get this changed, please contact Paul Eggert and his team from the [IANA timezone database](https://www.iana.org/time-zones). Tell them to move the old name to a legacy zone and add the new name as a new zone, so that older systems keep working.
> 
> Once a new version of the TZ database is released by IANA, this package will automatically reflect the changes.

@rogierschouten, thanks, do you have his contact, profile page here or LinkedIn?

**Comment by rogierschouten** [comment]
@shlomisas  See section 'Changes to the TZ database' on [this page](https://data.iana.org/time-zones/tz-link.html)

**Comment by shlomisas** [comment]
> Changes to the TZ database

@rogierschouten Done, thanks. 

So after the fix on their side we just need to `npm install` again?

**Comment by rogierschouten** [comment]
Yeah it will take me a couple of days to update this but it will be a bugfix version so it should automatically be picked up with your npm install

**Comment by ian-abbott** [comment]
The change has already been made (in the TZ maintainer's git repository) here:
https://github.com/eggert/tz/commit/e13e9c531fc48a04fb8d064acccc9f8ae68d5544

So it should appear in the next release of tzdata, which will probably be release 2022b.

**Comment by shlomisas** [comment]
> The change has already been made (in the TZ maintainer's git repository) here: [eggert/tz@e13e9c5](https://github.com/eggert/tz/commit/e13e9c531fc48a04fb8d064acccc9f8ae68d5544)
> 
> So it should appear in the next release of tzdata, which will probably be release 2022b.

Yeh, Paul Eggert also replied to me:

> That change was done a couple of weeks ago, as reported here:
> https://mm.icann.org/pipermail/tz/2022-April/031381.html

When the next release of tzdata [in NPM](https://www.npmjs.com/package/tzdata) should happen?

**Comment by rogierschouten** [comment]
when the IANA TZ database is released, i will get an email. I always update this package within a few days from that (and I cannot do it before that). Currently they are still on version 2022a

**Comment by ian-abbott** [comment]
> When the next release of tzdata [in NPM](https://www.npmjs.com/package/tzdata) should happen?

 As @rogierschouten mentions, not until the next tzdata release. Those are sporadic, although there are usually at least two releases per year because there is always some government trying to change its country's time zone rules, usually at the last minute! I've been following the tzdata project long enough to know that a simple zone name change will not warrant a special release.

**Pull request closed without merging**
